# Generated by Django 2.1 on 2018-11-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorios',
            old_name='id_codigo',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='accesorios',
            old_name='id_cuarto',
            new_name='cuarto',
        ),
        migrations.RenameField(
            model_name='accesoriosactividades',
            old_name='id_accesorio',
            new_name='accesorio',
        ),
        migrations.RenameField(
            model_name='accesoriosactividades',
            old_name='id_actividades',
            new_name='actividades',
        ),
        migrations.RenameField(
            model_name='actividadesrealizadas',
            old_name='id_actividades',
            new_name='actividades',
        ),
        migrations.RenameField(
            model_name='actividadesrealizadas',
            old_name='id_reporte',
            new_name='reporte',
        ),
        migrations.RenameField(
            model_name='cuartos',
            old_name='id_piso',
            new_name='piso',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='id_cuarto',
            new_name='cuarto',
        ),
    ]
