# Generated by Django 2.1 on 2019-01-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='isReport',
            field=models.IntegerField(default=1),
        ),
    ]
