# Generated by Django 2.1 on 2019-01-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_reportes_isreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='isReport',
            field=models.IntegerField(default=0),
        ),
    ]
