# Generated by Django 2.1 on 2019-01-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20190123_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesrealizadas',
            name='realizado',
            field=models.DateTimeField(verbose_name='realizado'),
        ),
    ]
